### ISSUE TITLE
rich text editor issue

### ISSUE THREAD

**Issue by NorthstarTech** [ryandeba/grapesjs-html-block#2]
How to add the icon of ordered List in rich text editor? Here is my code. 

rte.add('insertOrderedList', {
	  icon: '',//how to add the icon of orderlist here??
	  attributes: {title: "Ordered List"},
	  result: (rte, action) => rte.exec('insertOrderedList'),
});

**Comment by ryandeba** [comment]
Hi @NorthstarTech - let's keep the discussion for this one over in the grapesjs project. I've responded here: https://github.com/artf/grapesjs/issues/572
