### ISSUE TITLE
borders in grapesjs

### ISSUE THREAD

**Issue by NorthstarTech** [ryandeba/grapesjs-html-block#4]
Is it possible to add border-top, border-right,border-left properties individually under the decoration heading in grapesjs. For now it only shows the border-width which gives all sided borders. I want only right or left sided borders.

Thanks

**Comment by ryandeba** [comment]
Hi @NorthstarTech, I'm going go close this issue because I think it is better suited in the core grapesjs project. I do not know the answer right now, but I will reply to this issue if I have time to look into it for you: https://github.com/artf/grapesjs/issues/575
